transport_protocol: 1
dest_service: "your-destination-service-name"
host_ports:
  - "localhost:8080"
  - "localhost:8081"

long_connection:
  min_idle_per_address: 5
  max_idle_per_address: 10
  max_idle_global: 20
  time_interval:
    unit: "s"
    value: 30

mux_connection: 4
rpc_timeout:
  unit: "s"
  value: 5
connect_timeout:
  unit: "s"
  value: 3

tag:
  key: "your-tag-key"
  value: "your-tag-value"

stats_level: 1
conn_reporter_enabled: true

grpc_conn_pool_size: 100
grpc_write_buffer_size: 1024
grpc_read_buffer_size: 1024
grpc_initial_window_size: 128
grpc_initial_conn_window_size: 1024
grpc_max_header_list_size: 8192

grpc_keepalive_params:
  time:
    unit: "s"
    value: 20
  timeout:
    unit: "s"
    value: 5
  permit_without_stream: true

http_connection: true
client_basic_info:
  service_name: "your-service-name"
  method: "your-method"
  tags:
    key1: "value1"
    key2: "value2"
